### ISSUE TITLE
Ability to use alternative "S3" providers

### ISSUE THREAD

**Issue by Gaz492** [niceit/tabby-cloud-sync-settings#1]
Have the ability to use alternative S3 compatible services such as Backblaze, minio etc

**Comment by niceit** [comment]
Yes, I will add in next release, I was thinking to add Wasabi, Digital Ocean Storage and your requested services. Please keep update it recently

**Comment by siccous** [comment]
Support for self-hosted Minio would be awesome, thanks.

**Comment by niceit** [comment]
@siccous I will add Minio in next version.

**Comment by niceit** [comment]
> Maybe also Azure Blob Storage, or Google Cloud Storage (their equivalents to S3),

Will be planned ahead!

**Comment by himslm01** [comment]
Do you know when the next version with alternate S3 providers may be available?
Being able to sync to a local minio will be awesome!

**Comment by niceit** [comment]
We will plan soon. Thanks!

**Comment by niceit** [comment]
yes, I'm planned please wait for next updates.

**Comment by niceit** [comment]
hi @all hope you love the plugin, we've just released version 1.5.0 and will support **S3 Compatibility Custom Storages**,
 you all could upgrade and try.

<img width="972" alt="CleanShot 2022-07-17 at 01 20 19@2x" src="https://user-images.githubusercontent.com/3917898/179367433-5e97956a-2c45-4cbd-8beb-a03b3efed8c2.png">


Please support us for more future contributions. 💪 💪
