### ISSUE TITLE
not able to connect to ftp

### ISSUE THREAD

**Issue by BangerTech** [niceit/tabby-cloud-sync-settings#10]
hey first of all thanks for your work. 
i´m trying to setup the ftp sync it works with filezilla for example but on tabby it says unable to connect with your settings. 
is there any hint? which port does sync use? 
thans

**Comment by BangerTech** [comment]
i´ve created the directory and file like in an old issue but this doesn´t help.
<img width="1384" alt="Bildschirmfoto 2022-01-05 um 14 17 46" src="https://user-images.githubusercontent.com/73241309/148223970-70c9c1cb-e353-4870-8bd6-56c01727643f.png">

**Comment by niceit** [comment]
Thanks for your report @BangerTech I will check and apply fixes in next release.

Regards
