### ISSUE TITLE
WebDav syncing with Nextcloud problem on other Device

### ISSUE THREAD

**Issue by FormBurden** [niceit/tabby-cloud-sync-settings#12]
Hi there,

great addon, works fantastic on the first device. But I'm having issues with syncing on a different device. Settings and everything to get the sync to work for Nextcloud works, everything is green. When I restart to hopefully see the settings, the "config file" within the settings has the same vault contents, with the crazy random cypher text, and it's the exact same as my first device. However, what doesn't work correctly, is the config above the vault is empty and doesn't show the same contents as the first device, where it has a bunch of the default config settings as well as the settings that get saved to the config file when you customize the profiles and such.

It seems though the Sync works, but either does not add more of the correct settings so it's identical to the sync from the first device. Like I said, the cypher text from the Vault is correct, but no other config setting shows above the vault cypher. So there is missing items. 

At least that's what I've concluded. Anything I can do? Or maybe this is a bug when trying to sync to other devices with WebDav over Nextcloud? All paths are correct.

**Comment by niceit** [comment]
Thanks for your report @FormBurden I will check and apply fixes in next release.

Regards

**Comment by FormBurden** [comment]
Not a problem. Forgot to mention: 

Tabby - Alpha 169
tabby-1.0.169-linux.deb - For Debian Install
Deb 11

I also have "Encrypt config file" ticked to on under Vault, if that helps at all.

**Comment by niceit** [comment]
Checkout new release
