### ISSUE TITLE
Planned - Upcoming Services

### ISSUE THREAD

**Issue by niceit** [niceit/tabby-cloud-sync-settings#13]
- Google Cloud Storage.
- Gists for Gitee, Bitbucket.
- Minio S3 alternative.
- Saving password, key file vault??... Good or bad security?
- Revision of setting changes??
- Multiple saved settings for cloud?? Now it just has one config at a time.
- Rich view for syncing log?? (currently saved to files)

**Comment by geirawsm** [comment]
Would love a setting that just saves the file to my Nextcloud-folder.
