### ISSUE TITLE
Plugin don't work, sync config invalid

### ISSUE THREAD

**Issue by PrzemekSkw** [niceit/tabby-cloud-sync-settings#17]
Hello, I install plugin cloud-settings-sync and add my ftp server. I test and it show OK, then ask to remove settings. When I restart Tabby my settings are gone. Is that plugin still working? I have always popup info on bottom:

![Zrzut ekranu_20220401181048](https://user-images.githubusercontent.com/25219988/161301804-7b436edd-494b-4fce-b4ac-f03c81d04a58.png)

I just add quick command (wchich is also don't work)
I have last Tabby debian file installed.
Regards

**Comment by MagicLike** [comment]
Same problem here, wasn't able to sync to NextCloud through WebDav

**Comment by niceit** [comment]
Please upgrade to Version 1.4.0 and try again!

**Comment by MagicLike** [comment]
@niceit 
Now I get the following error message, with the littel notification "Your settings had been removed:
![grafik](https://user-images.githubusercontent.com/82117109/169752252-b7d52a99-c990-4835-b3a0-823f10dedb79.png)

**Comment by niceit** [comment]
@MagicLike you should verify that the path at your config is having Write permission, this is error about the plugin is unable to write your config file at that location.

**Comment by MagicLike** [comment]
@niceit Do ysou mean write permission to the cloud or to the local config?

**Comment by niceit** [comment]
To the cloud @MagicLike

**Comment by MagicLike** [comment]
@niceit Thats weird, I created a new app password in my Nextcloud for Tabby, which should give write access...
When I test the connection everything seems fine:
![grafik](https://user-images.githubusercontent.com/82117109/169768232-5a04eb95-29e9-4a8d-87d5-fcad7a866b43.png)

**Comment by MagicLike** [comment]
I have already tried that, but then it immediately says "Unable to connect with your settings"

**Comment by aimai-who** [comment]
I got the exact same problem. And I'm using nextcloud, too. I use tabby on ubuntu 22.04,  tabby 1.0.179, cloud-settings-sync 1.4.1 .
It's very strange that only one of my pc has this problem. I also installed tabby and cloud-settings-sync on my laptop with same configuration(ubuntu, nextcloud with same account), and it works just fine.

**Comment by aimai-who** [comment]
> I got the exact same problem. And I'm using nextcloud, too. I use tabby on ubuntu 22.04, tabby 1.0.179, cloud-settings-sync 1.4.1 . It's very strange that only one of my pc has this problem. I also installed tabby and cloud-settings-sync on my laptop with same configuration(ubuntu, nextcloud with same account), and it works just fine.

Plus, on this pc, when I click "save this settings", it shows "sync file to the cloud failed ...", and the notification "Your settings had been removed" pops up, and the settings of cloud-settings-sync will not be stored. 

Additionally, if a valid tabby-setting.json is already on nextcloud, a window will pop and let me choose the sync direction. Whatever direction I choose, the sync will actually happen, but the settings of cloud-settings-sync will not be stored. Errors and notifications mentioned above still com up.

What else information should I provide?

**Comment by aimai-who** [comment]
![截图 2022-06-06 10-05-59](https://user-images.githubusercontent.com/90488946/172083930-d29be897-dd6d-44dd-891d-a4ed57ed45d6.png)

**Comment by niceit** [comment]
This could be closed, due to the user's invalid configuration
