### ISSUE TITLE
WebDav连接问题

### ISSUE THREAD

**Issue by yinxiulong** [niceit/tabby-cloud-sync-settings#2]
![image](https://user-images.githubusercontent.com/26619335/136973881-35ffec2f-1912-45ac-9e17-34d0793dd03a.png)

我只有把文件夹写在端口位置，才能正确的连接。要是我把文件夹写在端口下面的时候，加了斜杠/也会被替换掉。我没加斜杠的时候，也不会自动加。导致连接失败

**Comment by niceit** [comment]
okay, thank for noticing! I will take a look and adjust this change.

**Comment by wensley** [comment]
webdav我是怎么都连不上，ftp也连不上，等修复，谢谢！

**Comment by niceit** [comment]
hi @wensley  for connection error, you should check your WebDav settings and make sure it allows for remote login.

**Comment by wensley** [comment]
> hi @wensley for connection error, you should check your WebDav settings and make sure it allows for remote login.

I confirm that I can login and access on my computer's browser and mobile phone.
![2021-11-27 180258](https://user-images.githubusercontent.com/4245450/143676795-b3034243-0a77-478a-b2ce-1fa689ab5ee3.jpg)

**Comment by niceit** [comment]
Guys, see the solution here https://github.com/niceit/tabby-cloud-sync-settings/issues/3

**Comment by niceit** [comment]
> ![image](https://user-images.githubusercontent.com/26619335/136973881-35ffec2f-1912-45ac-9e17-34d0793dd03a.png)
> 
> 我只有把文件夹写在端口位置，才能正确的连接。要是我把文件夹写在端口下面的时候，加了斜杠/也会被替换掉。我没加斜杠的时候，也不会自动加。导致连接失败

Your port setting looks weird

**Comment by wensley** [comment]
> Guys, see the solution here #3
@niceit 
Nice!It's work! Thanks!
![屏幕截图 2021-12-13 171046](https://user-images.githubusercontent.com/4245450/145784061-039cfdc2-4875-4a12-8cd9-04bdbae2599d.jpg)

**Comment by niceit** [comment]
@all this should be resolved, thanks!
