### ISSUE TITLE
What is the difference between this synchronization and the synchronization that comes with Tabby?

### ISSUE THREAD

**Issue by DreamPWJ** [niceit/tabby-cloud-sync-settings#22]
![image](https://user-images.githubusercontent.com/16730031/173191209-088ca507-4d91-4d95-ab7b-403d3f73981a.png)

I lost all configuration using the sync that comes with tabby

**Comment by DreamPWJ** [comment]
Whether to support synchronization on the web, sometimes you need to operate ssh on the web?

**Comment by DreamPWJ** [comment]
Does not support github that will synchronize the configuration?

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/173191700-721e02e3-c6d9-4723-b090-70d3ac7ee4a2.png)

Github shèzhì wúxiào
10 / 5,000
翻译结果
github settings are invalid

**Comment by niceit** [comment]
@DreamPWJ You should understand how Gists works

**Comment by niceit** [comment]
> ![image](https://user-images.githubusercontent.com/16730031/173191209-088ca507-4d91-4d95-ab7b-403d3f73981a.png)
> 
> I lost all configuration using the sync that comes with tabby

I can't tell, you used this built-in Tabby, you should post your question to Tabby discussion group

**Comment by DreamPWJ** [comment]
Whether to support synchronization on the web, sometimes you need to operate ssh on the web?

**Comment by DreamPWJ** [comment]
What is the difference between this synchronization and the synchronization that comes with Tabby?

**Comment by niceit** [comment]
> Whether to support synchronization on the web, sometimes you need to operate ssh on the web?

Tabby itself does not support Web platform plugin

**Comment by DreamPWJ** [comment]
What is the difference between this synchronization and the synchronization that comes with Tabby?

**Comment by niceit** [comment]
> What is the difference between this synchronization and the synchronization that comes with Tabby?

The`synchronization that comes with Tabby` that is Official plugin built by Tabby owner, this one is a custom plugin.

**Comment by DreamPWJ** [comment]
I mean what is the difference in functionality

**Comment by DreamPWJ** [comment]
It seems that it is no different from the synchronization that comes with tabby. The choice is temporarily useless.
