### ISSUE TITLE
bug: synchronization failed with Cloudreve as WebDAV server

### ISSUE THREAD

**Issue by yanranxiaoxi** [niceit/tabby-cloud-sync-settings#23]
Tried a workaround in a different issue (remove port). Test Connection succeeds, but the upload fails when I Save This Setting.

If I specify a subfolder in the Host input box, the folder can be created. But uploading the file always fails.

I'm sure that using the WebDAV server synchronization within other software (Enpass & Windows Files Explorer) is fine, so the problem is most likely with the plugin or how I configured it.

Hope it is resolved. THX!

**Comment by yanranxiaoxi** [comment]
Here is my configuration:

Services: WebDav
Host: https://cloud.example.com/dav
Port:
Hostname or email: admin@example.com
Location: /
Password: ******

![00VV6%O@6ML}FVHRH_5 LTT](https://user-images.githubusercontent.com/10684000/175206901-0fb96cb7-7c59-4eea-a674-46e863cb596a.png)
![G@V% 36 KATN~%2E (4%X68](https://user-images.githubusercontent.com/10684000/175206910-60f9f3fb-30c5-49a0-a208-276d743b68ce.png)

**Comment by Geekaz** [comment]
Same here... when using nextclound with webdav the port needs to be removed from the sync config as otherwise it will try to use the port as a subfolder (apache2 log):

PUT /remote.php/dav/files/<username>:443/tabbytest.txt HTTP/1.1" 404 7443
which of course fails...

another workaround is to separate the address from the path e.g.

![image](https://user-images.githubusercontent.com/17447393/175489204-0c79f1b2-b3f6-4b98-8065-0ea169e851de.png)

maybe this could be handled by the plugin itself (e.g. split the url into host and folder before adding the port)

Second issue is when syncing the settings it searches for tabby-setting.json which is of course not there at the first upload (apache2 log):
PROPFIND /remote.php/dav/files/<username>/tabby/tabby-settings.json HTTP/1.1" 404 7640

manually creating an empty tabby-settings.json helps and it then asks to upload the config which works (it is then made available on nextcloud) but the plugin still shows "sync file to the cloud failed".

**Comment by yanranxiaoxi** [comment]
https://github.com/niceit/tabby-cloud-sync-settings/issues/23#issuecomment-1165309056

After seeing your operation, I also tried to create a new tabby-setting.json file on Cloudreve, which added a pop-up window, but the error still exists.

Like...
![image](https://user-images.githubusercontent.com/10684000/175491991-f6d7e420-8473-4970-ac59-0e106f2d1438.png)

The error is the same as yours.

**Comment by kakioff** [comment]
![屏幕截图 2022-06-25 133915](https://user-images.githubusercontent.com/64448740/175759974-c03042cc-d31a-4a05-a66e-525dcc99c419.png)
![屏幕截图 2022-06-25 133915](https://user-images.githubusercontent.com/64448740/175759994-63a45f3e-a347-4836-ad9a-f56eae1081dd.png)

![屏幕截图 2022-06-25 133915](https://user-images.githubusercontent.com/64448740/175760005-47a17027-f1a0-40f7-91c7-e65821bce2c0.png)

![2022-06-25](https://user-images.githubusercontent.com/64448740/175760097-20eb0022-db28-4bb8-a4e8-cbdc5a347f48.png)


我几乎试了所有方法都不行，一度以为是我服务器的问题

tabby  v1.0.181
cloud-sync v1.4.2

**Comment by yanranxiaoxi** [comment]
https://github.com/niceit/tabby-cloud-sync-settings/issues/23#issuecomment-1165316415

Errata, manually create a new tabby-setting.json file in this way and synchronize it, and after you select upload the local configuration, the content you need will be stored in the tabby-setting.json file on the WebDAV server. However, the Tabby client still prompts the synchronization failure.

**Comment by niceit** [comment]
This is an old issue, please checkout this Thread resolved before
https://github.com/niceit/tabby-cloud-sync-settings/issues/3

**Comment by yanranxiaoxi** [comment]
> This is an old issue, please checkout this Thread resolved before #3

I noticed the issue, but I still couldn't solve the problem by using the solution inside.

The connection can be successfully tested without entering a port. But at this time the server does not create the json file.

After the server manually creates the json file, select "Upload Local Configuration" in the pop-up window, and the json file on the server can be filled correctly. However, the client still has the following prompt that cannot be saved.

![image](https://user-images.githubusercontent.com/10684000/175783661-2dbabc6c-96be-4a97-b760-90ae6a0504ef.png)

So I still can't achieve the desired function. If this may be a bug that can be solved, I would be willing to provide a Cloudreve user account and a WebDAV user account for testing.

**Comment by niceit** [comment]
@yanranxiaoxi which service are you using?

**Comment by yanranxiaoxi** [comment]
> @yanranxiaoxi which service are you using?

A self-hosted instance of Cloudreve.

https://github.com/cloudreve/Cloudreve

**Comment by niceit** [comment]
Could you create me a demo account? I will help to check

**Comment by yanranxiaoxi** [comment]
https://dpaste.org/hPOLC

Above is the information I think you will need.

Thanks again!

**Comment by yanranxiaoxi** [comment]
> Could you create me a demo account? I will help to check

The message above forgot to mention you.

The links below contain information about the test account:

https://dpaste.org/hPOLC

**Comment by yanranxiaoxi** [comment]
@niceit  The message above forgot to mention you.

The links below contain information about the test account:

https://dpaste.org/hPOLC

**Comment by aimai-who** [comment]
感谢楼主。我在另一个issue里（  #17  ）也反馈了这个问题，但是没有得到作者的重视。

**Comment by yanranxiaoxi** [comment]
> 感谢楼主。我在另一个issue里（ #17 ）也反馈了这个问题，但是没有得到作者的重视。

@aimai-who In NextCloud, the WebDAV address should be https://drive.example.com/remote.php/webdav/

I can connect correctly if I use the above address and do not fill the Port field.

**Comment by ginebib** [comment]
Same error as @yanranxiaoxi described here with Nextcloud. Settings are valid and after saving, it uploads the config once (after saving an empty tabby-settings.json), but at the same time it says "sync file to the cloud fails" and it drops the settings.

Tabby 1.0.181
Cloud Sync Settings 1.4.2
Nextcloud 24.0.1

**Comment by niceit** [comment]
@all Guys, you could upgrade to version 1.4.3 and use the Upload Local Settings if you have problem with first time sync settings to the cloud.

**Comment by yanranxiaoxi** [comment]
@niceit Thank you for your efforts! 🎉

![image](https://user-images.githubusercontent.com/10684000/177127578-14501550-ff14-4ebf-bbb1-b71fbf544e1e.png)

The configuration test was successful.

**Comment by niceit** [comment]
The upgrade is managed by Tabby, you could go to plugins section and upgrade the plugin to newer version.

**Comment by aimai-who** [comment]
> The upgrade is managed by Tabby, you could go to plugins section and upgrade the plugin to newer version.

Thank you for the reply. But I can't see teh newer version in tabby. Maybe my network has some problem.

**Comment by yanranxiaoxi** [comment]
@aimai-who If you don't have a way to update automatically within Tabby, you can try replacing the files manually.

The following is the 1.4.3 version package:

https://registry.npmjs.org/terminus-cloud-settings-sync/-/terminus-cloud-settings-sync-1.4.3.tgz

**Comment by aimai-who** [comment]
> > 感谢楼主。我在另一个issue里（ #17 ）也反馈了这个问题，但是没有得到作者的重视。
> 
> @aimai-who In NextCloud, the WebDAV address should be https://drive.example.com/remote.php/webdav/
> 
> I can connect correctly if I use the above address and do not fill the Port field.

Thank you! But I had to set up a special port for my nextcloud, because my nextcloud is hosted in my homelab, and 80/443 is forbidden here for home client.
I had succeeded in test connection by the blow settings.
Host: https://my.domain.name
User: my_user_name
Password: ****
Port: 8888
Location: /remote.php/dav/files/my_user_name/tabby_sync (tabby_sync is the directory I created for the json file)

**Comment by yanickxia** [comment]
@niceit  PLS, update gitub release version. [cloud-settings-sync](https://www.npmjs.com/package/terminus-cloud-settings-sync)  newest than [github](https://github.com/niceit/tabby-cloud-sync-settings/releases/)
