### ISSUE TITLE
Sync file to the cloud failed

### ISSUE THREAD

**Issue by Paulpatou** [niceit/tabby-cloud-sync-settings#26]
Hi,
I'm trying to re-configure (new install on my computer) cloud sync with webdav.
When I test the connection it works well I have the log on my webdav server =>
![image](https://user-images.githubusercontent.com/33478981/182776158-db16eff1-e6d0-4abc-a467-bf3db7726e30.png)

But when I save it I get this error =>
![image](https://user-images.githubusercontent.com/33478981/182776701-6e41963b-16f8-4ac9-8871-6bc1890870af.png)

After that the configuration has been synchronized but I can't modify my ssh connections
Another error appears =>
![image](https://user-images.githubusercontent.com/33478981/182777659-4dd59091-8163-476c-81d1-af90cebb3eeb.png)

**Comment by niceit** [comment]
Please take a look at closed issue with WebDav, the solution were added by the users.
