### ISSUE TITLE
Loging cloud credentials

### ISSUE THREAD

**Issue by birkanozer** [niceit/tabby-cloud-sync-settings#27]
Hi there
I realised today that this plugin prints logs of each transaction to the cloud. The problem is it also print cloud login credentials to a plain text file which is veeery insecure.

**Comment by niceit** [comment]
that is your log under your pc I think, it printed out for you to debug later why it got failed or something.

**Comment by birkanozer** [comment]
Yes, I know that, but logging cloud credentials to a text file is risky. At least, there should be a setting to turn on and off the logging.

**Comment by niceit** [comment]
@birkanozer I will note this setting in next release

**Comment by niceit** [comment]
Updated at version 1.5.2
