### ISSUE TITLE
Doesn't get values from cloud 

### ISSUE THREAD

**Issue by birkanozer** [niceit/tabby-cloud-sync-settings#28]
Hi again,
I used this plugin to backup all my settings and ssh profiles. The backup file size is around 40kB. Then I deleted Tabby and installed it on a different driver on the computer. When I try to retrieve old settings plugin creates a new file on the remote server which is around 18kB in size. It gets SSH keys in the vault but doesn't get SSH profiles.

**Comment by birkanozer** [comment]
I tackled a little bit more. Turns out that it doesn't get the vault too. I'm using Digital Ocean Spaces as a remote. It seems that whatever option I choose for synching, the plugin first updates the cloud with local settings and then checks if the cloud backup is recent or not.  I couldn't get old settings to the new installation.

**Comment by niceit** [comment]
I think you're the first one faced this issue, could you provide more details information so I could help to take a look?

**Comment by birkanozer** [comment]
Hi again,
I tried the plugin again. Before I start, I removed the Tabby installation and deleted the /AppData/Roaming/tabby folder. I downloaded a fresh copy of the portable version of the Tabby. I unpacked it into the C/Program Files/Tabby folder.

I had the old settings from the old installation. It was backed up to DigitalOcean Spaces with this plugin. 
![old settings](https://user-images.githubusercontent.com/7575650/185349220-dda13e8e-2334-4a97-9892-990c3643a2dc.png)

Then I opened the fresh installation of the Tabby which I mentioned above. I entered the cloud credentials. Then, I tried the test connection. Old settings are still 40kB.
![test connection](https://user-images.githubusercontent.com/7575650/185349618-d2ece13d-49a4-4da8-aba0-09ab14da52b1.png)

After, I saved the cloud settings. I chose "Sync Cloud Settings" option. Then restarted the Tabby.
![chosen setting](https://user-images.githubusercontent.com/7575650/185350019-b40552c6-1a4d-4064-9cac-7dafb1b9392c.jpg)

Tabby opened with default config. The vault was deleted and connection profiles are wiped. The backup file seemed to be re-uploaded with a smaller file. 
![final result](https://user-images.githubusercontent.com/7575650/185350423-dcd52ae2-3896-4495-bce1-32ee26b3a36c.jpg)

I closed the Tabby again. And reuploaded the old settings again. 
![reuploaded settings](https://user-images.githubusercontent.com/7575650/185350636-43f1b52a-f6c8-40eb-95d1-31ebabc37d2f.jpg)

I opened the Tabby again. I prompted the vault password. Meantime I checked the cloud files and I saw that the backup file changed again with a file which is 412B in size. 
![reopenned before vault passwd](https://user-images.githubusercontent.com/7575650/185350809-acce8e5b-dd86-492c-982b-dfa12496be7b.jpg)

I entered the vault password again. Tabby opened. I checked the file size on the cloud again. The file is replaced again with a file which is 752B in size. The vault and the profiles are still missing. 
![reopenned after vault passwd](https://user-images.githubusercontent.com/7575650/185351401-e75903c2-f4b3-49db-a6b1-60e22f0dbb84.jpg)

Logs are here 
[test.log](https://github.com/niceit/tabby-cloud-sync-settings/files/9371964/test.log)

**Comment by birkanozer** [comment]
Btw, I decoded tabby-settings.json file with this script. 

https://gist.github.com/birkanozer/9b645321c98d9712357c6263de2612ef

**Comment by niceit** [comment]
I think the problem while you are using Tabby vault then set the password, the plugin doesn't support yet, I will update soon

**Comment by AndreasW79** [comment]
Any news on that? Did i get it right - this sync doesnt currently support encrypted settings / vault settings?

Thanks in advance.

**Comment by niceit** [comment]
The plugin does not work with the Tabby Vault, you could disable this plugin and use the Tabby vault instead.

**Comment by AndreasW79** [comment]
Thanks. Does not work is the same as is not planned to work with? I prefer this plugin because i can use my own server....

**Comment by niceit** [comment]
@AndreasW79 it's planned in the future but not so soon, the vault is based tabby application.
Keep in touch.
