### ISSUE TITLE
ability to sync with gitlab on prem 

### ISSUE THREAD

**Issue by karaliot** [niceit/tabby-cloud-sync-settings#29]
Hi there, 

thanks for creating and sharing! Are you considering adding the option to users to use gitlab on prem rather than the cloud service? If I'm not terribly mistaken it could mean to let users fill in the gitlab url...

Thanks again!

**Comment by niceit** [comment]
hi @karaliot currently the plugin does not support the feature you wish. You could use Gitlab snippet as it was supported.
