### ISSUE TITLE
webdav unable to connect with your settings

### ISSUE THREAD

**Issue by qliang0816** [niceit/tabby-cloud-sync-settings#3]
cannot connect to jianguoyun,teracloud webdav server.

**Comment by niceit** [comment]
hi @qliang0816 for connection error, you should check your WebDav settings and make sure it allows to remote login.

**Comment by foreversos** [comment]
> hi @qliang0816 for connection error, you should check your WebDav settings and make sure it allows to remote login.

i tested
cannot connect to jianguoyun
please test:
https://www.jianguoyun.com/

**Comment by qliang0816** [comment]
> 

still unable to connect

**Comment by BOFH90** [comment]
Same problem with Nextcloud Webdav. Works with other Clients, but not with Tabby-Cloud-Sync

**Comment by niceit** [comment]
Thanks, I will look into this issue and update fixes.

**Comment by niceit** [comment]
Hey guys, I just do a quick check, for Teracloud you don't need to put in the Port, just leave it empty, could you try this way for other WebDav servers you had?

![image](https://user-images.githubusercontent.com/3917898/145781077-aa66fa40-5bd4-4500-b37f-3d787d7ee4ae.png)

**Comment by BOFH90** [comment]
Yes, Leaving the Port empty works with Nextcloud too

**Comment by qliang0816** [comment]
坚果云不生效
![1639411350(1)](https://user-images.githubusercontent.com/24631867/145846063-7eb9af90-5022-4cd8-8a73-4bf593e03f9e.png)

**Comment by studycwq** [comment]
> 坚果云不生效 ![1639411350(1)](https://user-images.githubusercontent.com/24631867/145846063-7eb9af90-5022-4cd8-8a73-4bf593e03f9e.png)

路径直接写到链接后面就可以了
![Snipaste_2021-12-20_11-02-58](https://user-images.githubusercontent.com/1407451/146705937-7662fa6e-778b-4c05-824a-b5b62e00dbb7.
![Snipaste_2021-12-20_11-03-39](https://user-images.githubusercontent.com/1407451/146705962-5be3b76d-954f-4a32-90d8-d92e0dcadbbd.png)
png)

**Comment by foreversos** [comment]
> 

根据提示,我也连接成功了

**Comment by qliang0816** [comment]
需要先创建对应json文件，之前使用dav.dropbox的时候自动创建了。
感谢各位大佬。

**Comment by niceit** [comment]
@all this should be resolved. thanks
