### ISSUE TITLE
Removes saved config

### ISSUE THREAD

**Issue by t4ov** [niceit/tabby-cloud-sync-settings#32]
Hello, 
  I am using cloud sync with backblaze B2, but i have an issue, that when i create a new profile, after a few min it is gone. This happens when cloud sync is on. Any ideas how to troubleshoot it?
  OS: Windows 11
  Tabby: 1.0.183

**Comment by yushaye** [comment]
I have the same issue, tabby-cloud-sync-settings version is 1.5.1 and the tabby version is 1.0.186.

**Comment by niceit** [comment]
@t4ov could you provide me more details above this issue? I can not investigate with this short of description

**Comment by spaceproj** [comment]
Hello, I was trying to sync the config between Mac OS and Linux machine, and I faced a similar issue. I've configured the plugin to use GIST and the config file is correctly uploaded.
After that, I created a new profile to store SSH credentials. Once the sync task got executed, the profile has been automatically deleted, and of course, it has not been synchronized to the second machine.

**Comment by maxbuelk** [comment]
Hi, I am facing the same problem. Every setting I change or profile I add is removed whenn I restart Tabby. The tabby-settings.json gets updated on the cloud.
OS: Windows 11
Tabby: 1.0.188
Cloud Sync Setting: 1.5.2
WebDav with 10 seconds interval

**Comment by hand32** [comment]
Me same here.
OS: Windows 11 & MAC
Using Gist.

Once the config uploaded, it changes to default(maybe?) setting after the sync is executed.

**Comment by SpookOz** [comment]
Yeah - either I haven't fully understood how this is supposed to work, or I'm missing something. It seems to me (webdav) that the config.yaml file gets overwritten by whichever client opens last. So if I add a connection on my desktop (linux) then open Tabby on my laptop (also Linux), instead of downloading the config.yaml from webdav to the laptop, it overwrites the file in webdav with the older one, then the desktop downloads it and effectively wipes any changes I have made.

**Comment by zuilintan** [comment]
> 是的 - 要么我还没有完全理解它应该如何工作，要么我错过了什么。在我看来（webdav），config.yaml 文件会被最后打开的客户端覆盖。因此，如果我在桌面（linux）上添加一个连接，然后在笔记本电脑（也是 Linux）上打开 Tabby，它不会将 config.yaml 从 webdav 下载到笔记本电脑，而是用旧文件覆盖 webdav 中的文件，然后桌面会下载它并有效地清除我所做的任何更改。

...It's terrible.

**Comment by niceit** [comment]
@zuilintan it's not about good or terrible, I made it free and opensource, you could browse the code and adjust per your need, use at your own risk.

**Comment by gideonstar-git** [comment]
Plugin description: "With this plugin you could sync your settings (Including saved SSH Sessions) automatically across devices."

Because of this error, it does not do exactly that. I have the same problem.

**Comment by MNLierman** [comment]
I may be misunderstanding this issue report, but it appears by examining the comments, that my issue report may be identical to this one. However, I want to clarify that I have **not** setup any other devices to sync with or to. When Gist sync is setup using this plugin, the changes are wiped out every sync. For some reason it's not correctly uploading the changes made. When installing this plugin, I lost all of my saved profiles and keys – not good. Nothing is synced actually. The only thing this plugin seems to do for me is wipe out any changes made.

@niceit

**Comment by niceit** [comment]
Should be closed for now

**Comment by MNLierman** [comment]
I mean, if I am being honest, this is not a solution and still a bug. It
still cannot sync if the vault is turned on. I think you should make that
clear in the description if you are not supporting that type of
configuration then it should be made crystal clear that this will not work
and you do not support the vault feature. I have not tried it with the
vault, but still not sure why having the vault turned on would cause the
plugin to malfunction and wipe out the config every time. There's something
wrong with the way that it's syncing.
