### ISSUE TITLE
windows and mac using the same config in cloud ,can the hotkey sync by OS or give a option that not to sync?

### ISSUE THREAD

**Issue by h496336011** [niceit/tabby-cloud-sync-settings#35]
my windows and mac using the same config in cloud ,can the hotkey setting sync by OS or give an option that not to sync?
now i have a windows and a macos, i hope i can use each system's own hotkey

**Comment by niceit** [comment]
hi @h496336011 The plugin just helps to sync the settings, about the settings it's self, it will be managed and loaded by Tabby main application.

**Comment by h496336011** [comment]
I got it ,it's Inefficient for plugin to resolve the settings ,It's the main application's job to distinguish different OS hotkey or other special options. But I think it might require some cooperation between you and the main app. Once it comes to cooperation, it's hard to move forward  : (
and thanks for this plugin ,it help me a lot
