### ISSUE TITLE
config can not be downloaded accross platform via webdav

### ISSUE THREAD

**Issue by wurenny** [niceit/tabby-cloud-sync-settings#37]
# envs
| Device | OS | Tabby | Cloud sync setting |
|-|-|-|-|
| Device1 | Linux Mint 20.3 | A187 | 1.5.2 |
| Device2 | Windows 10 | A187 | 1.5.2 |

* sync serivce type: webdav

# problem
* save setting
![image](https://user-images.githubusercontent.com/6622574/209470694-c8ac60bf-057c-4d45-b19a-80e61ffdf362.png)
* select: sync cloud setting
![image](https://user-images.githubusercontent.com/6622574/209470688-d6268bda-30a9-453e-ab1c-2dc374f69503.png)
* see error:
![image](https://user-images.githubusercontent.com/6622574/209470692-59b09a88-31cb-412b-a975-76c8485d09d3.png)
* the devtool console display nothing

# analysis
I found that the configuration uploaded on Linux does not apply to Windows. The message: Your sync config is invalid.

I think this may be because some configuration items do not support cross-platform use, such as shortcut keys(just example), so different platforms cannot use the same configuration file, which may require some mapping calculation of these configurations, and then generate a configuration file that tabby can recognize on the current operating system

**Comment by niceit** [comment]
hi @wurenny thanks for reporting.
I will take a look into it 👍

**Comment by z0ow** [comment]
@wurenny @niceit I got same issue when using the WebDAV service to sync configuration between two PCs. So I guess another possibility is some data was wrongly transferred with WebDAV.

**Comment by niceit** [comment]
The version 1.6.0 will be released soon. Please upgrade once it's released.

**Comment by niceit** [comment]
Should be closed.
