### ISSUE TITLE
About "Encrypt config file" Option

### ISSUE THREAD

**Issue by amefs** [niceit/tabby-cloud-sync-settings#42]
When the "Encrypt config file" option is enabled in the Vault tab, all data is encrypted as follows:

```yaml
vault:
  version: 1
  contents: >-
--------------------------
```

However, after decrypting the Vault in Tabby, it should be restored to a non-encrypted configuration file along with the Vault that stores the password. These two components are essential for Tabby to function properly. It's important to note that the automatic synchronization of "tabby-cloud-sync-settings" only synchronizes the Vault that stores the password; the configuration section is not synchronized.

Does this imply that the current "tabby-cloud-sync-settings" is incompatible with the "Encrypt config file" option? Is there any plan to provide support for this in the future?

**Comment by niceit** [comment]
Please don't encrypt config file with Tabby while using this plugin, otherwise you could use Tabby sync feature (You should set up yourself), per my point of view that setting has buggy and you will lose your settings and never got it back.
