### ISSUE TITLE
Backblaze Region How to get it?

### ISSUE THREAD

**Issue by moshin34** [niceit/tabby-cloud-sync-settings#44]
The link in the app "how to get backblaze region" seems to be broken. 

Can you help point me in the right direction?

Thanks

**Comment by yt1988** [comment]
The URL link is still inaccessible. Do I need to wait for the version to update? Or can you give the method of obtaining the backblaze region code directly?

**Comment by moshin34** [comment]
I can check for you later, but after trial and error I think its the part
after the s3, and before the rest of the FQDN.  Just enter that one bit.
for me it was US-East-005, tabby adds everything before and after.   Hope
this helps
