### ISSUE TITLE
Syncing configs reached Github's API rate limit

### ISSUE THREAD

**Issue by Vincent-HD** [niceit/tabby-cloud-sync-settings#48]
Hi !
For some reason, the syncing reached the limit of Github's API, the gist had like 3700 revisions, not clear what happened

![image](https://github.com/user-attachments/assets/1e5b1240-8b56-449c-9855-610a575f19e8)

**Comment by niceit** [comment]
Let's use another cloud service, Github won't allow user to call their gist service in huge amount. Also their gist is not a good service to be synced the setting any further.
