### ISSUE TITLE
Add more sync methods

### ISSUE THREAD

**Issue by MrFireDevil** [niceit/tabby-cloud-sync-settings#5]
Hello, can you add google drive or other methods to sync settings? All currently methods are not really for free 😓
So that you can log in with Google and that you can choose a folder where it should be saved. 

I would help you, but I don't understand the programming language you use to program the plugin.

PS: Sry for my really bad English 😅

**Comment by pquerner** [comment]
Maybe it can add Github Support. Like ask for a token and then create a secret gist (or better private repository?)
Github Account is free and pretty sure every dev has one ?

**Comment by MrFireDevil** [comment]
Yes, this is a really good idea 👍🏻

**Comment by niceit** [comment]
Added Gist for Github & GitLab at version 1.3.0

**Comment by MrFireDevil** [comment]
Thank you very much!
