### ISSUE TITLE
FTP-FTPS Connection Problem

### ISSUE THREAD

**Issue by Ando-lm** [niceit/tabby-cloud-sync-settings#56]
Hi there is a little problem with ftp-ftps connection.
When i configure the connection the "Test Connection" is passed, but when I click "Save This Settings" I had an error connection refused.
The problem is the custom port I set in my public ftp server. If you see the screen attached, despite having set port 2000 the error say "connection refused in port 21".
If i set mi ftp-server service on standard port 21 everything is ok.

![Screenshot 2024-12-12 alle 16 27 50](https://github.com/user-attachments/assets/f7c201a5-38a4-415a-bf2f-23b4eb063a26)

**Comment by niceit** [comment]
There are different types of connections to FTP depending on your server, you could do the trick that worked for you.
