### ISSUE TITLE
Plugin Completely Unusable! - Every Sync Deletes Saved Config

### ISSUE THREAD

**Issue by MNLierman** [niceit/tabby-cloud-sync-settings#57]
**Issue Report:** Tabby Cloud Sync Settings Plugin; **Status: Completely Unusable**

**Environment:**
- Tabby Cloud Sync Settings version: 1.6.5
- Tabby version: Latest
- Operating System: Windows 11 24H2

**Description:** This Tabby Cloud Sync Settings plugin is currently unusable. Immediately after enabling the plugin, setting it up, and configuring a sync location (in this case, syncing to GitHub secrets using an API key), the plugin cleared my entire configuration and all profiles. Every subsequent sync continues to do this, despite the logs showing "Sync direction: local to cloud"

I was quite upset by this plugin initally wiping out all of my saved profiles, but hoped it was a one-time issue. Unfortunately, this was not the case. Every time the plugin syncs, it removes and wipes out all configuration changes.

**Steps to Reproduce:**

1. Enable the Tabby Cloud Sync Settings plugin.
2. Configure the sync location, I chose GitHub secrets using an API key, but I'm unsure this matters.
3. Observe that the entire configuration and profiles are cleared.
4. Attempt to reconfigure any settings.
5. Notice that every subsequent sync removes all changes.
6. Logs: The logs indicate that the plugin is syncing from local to cloud and then states, "Your saved settings were synced." This event causes the current configuration to be wiped out.

Example: While selecting a color scheme and customizing colors, my changes were completely removed, and the default color scheme was reselected. At that moment, another "Your saved settings were synced." entry was logged in the plugin. This was observed over and over.

**Impact: At this time, the plugin is completely unusable as it consistently wipes out all configuration changes upon syncing.**

**Debugging:** Unfortunately, there aren't any options to enable verbose or debug logging, so I'm unable to provide additional details. The Gist appears to change with each sync, but since it's encrypted, I can't determine its contents. My expectation is that the plugin should detail the sync location and specify whether local settings were synced to the cloud or vice versa. If local settings were synced to the cloud, there should be no modification of local files. However, local files are being modified and replaced, indicating either an incorrect sync direction or erroneous code in the local-to-cloud sync option when using GitHub Gist.

**Tested v1.5.2: Conclusion – same behavior.** While configuring colors, the plugin replaced local settings again and overwrote everything. This includes the Tabby welcome page and analytic settings, meaning all settings are replaced.

**Edit 12-15-2024:** It appears that https://github.com/niceit/tabby-cloud-sync-settings/issues/32 may be the same bug. I was originally doubtful this was the case, but upon closer inspection of the comments, it appears that the issue I'm experiencing has been reported for over 2 years.

![image](https://github.com/user-attachments/assets/e4e7967d-7509-4835-aa5e-649b446f7166)

**Comment by MNLierman** [comment]
I would like to add an additional bug: When attempting to submit feedback within the plugin, it errors out with "status code 500" even after multiple attempts.


![image](https://github.com/user-attachments/assets/ff605258-0e73-483d-9be5-86c312f84135)

**Comment by ilbarone87** [comment]
I'm actually having the same issue. Windows client.

**Comment by MNLierman** [comment]
> I'm actually having the same issue. Windows client.

Are you using the Gist sync method? I found another sync plugin using the plugins section of Tabby, and that one seems to work, albeit it's a much simpler plugin – but it syncs one-way and allows manual downloading of the configuration data saved in Gist.

**Comment by w4e997** [comment]
Please don't encrypt config file with Tabby while using this plugin, otherwise you could use Tabby sync feature (You should set up yourself), per my point of view that setting has buggy and you will lose your settings and never got it back.

**Comment by ilbarone87** [comment]
> > I'm actually having the same issue. Windows client.
> 
> 
> 
> Are you using the Gist sync method? I found another sync plugin using the plugins section of Tabby, and that one seems to work, albeit it's a much simpler plugin – but it syncs one-way and allows manual downloading of the configuration data saved in Gist, which one would use if changed were saved on another PC.

No, I sync to an s3 bucket that indeed is the major reason I wanted to transition to Tabby.

**Comment by niceit** [comment]
Yes per this point
> Please don't encrypt config file with Tabby while using this plugin, otherwise you could use Tabby sync feature (You should set up yourself), per my point of view that setting has buggy and you will lose your settings and never got it back.

if you want  to use  Tabby built-in sync plugin, in  case disable my plugin or  uninstall  it, don't mix  them  together

**Comment by MNLierman** [comment]
I'm not mixing the sync plugins. I'm using the standard Tabby vault options which encrypts passwords and key files, but otherwise handles config files in the default fashion. With those default options in mind, the behavior I outline in the description of this report is how this plugin is working. On a brand new config blank slate, because this plugin wiped out my settings, it doesn't sync at all. It simply wipes out your current settings, and I have no idea what it uploads to Gist.
@niceit

**Comment by niceit** [comment]
@MNLierman if you set the master password and encrypted the config file, I cannot guarantee the plugin will work well with the encrypted config. The last hope for you to  recover your previous config, please follow the steps below:

1. Unload or uninstall this plugin,  then shut down the application.
2. Locate the Tabby config folder (see this link https://github.com/Eugeny/tabby/wiki/Config-file).
3. Look if you can see the backup file : **config.yaml.backup**
4. If you saw that file, copy the current one **config.yaml**   to some other place.
5. Rename  **config.yaml.backup** to **config.yaml**

Then open the application again. Good luck.

Again this plugin will not work if the master password is set or built in the plugin, decide which one you will use.

**Comment by MNLierman** [comment]
Thank you for your response! While retrieving my previous profile/config isn't a primary concern for me at this moment, I appreciate the information and will look into it. My main focus is getting the plugin to function correctly. It seems that other users are experiencing similar issues. Are you suggesting that the vault functionality is completely unavailable if I am using this plugin?

One of the key reasons for using Tabby is its ability to securely encrypt passwords and key files, and I need this to happen across multiple computers. The synchronization direction (one-way or adjustable per device) isn't a concern for me, as long as I can add passwords on one computer and be able to sync the configuration onto another using this plugin. While alternatives like OneDrive and rsync are options, the simplicity and universality of this plugin are what drew me to using Tabby specifically.

**Comment by niceit** [comment]
@MNLierman 
> vault functionality is completely unavailable if I am using this plugin?

Yes, if you use Vault password protected or Tabby built-in sync, please consider remove this plugin to prevent  conflicting.

**Comment by niceit** [comment]
Should be closed for now
