### ISSUE TITLE
FTP "Test Connection" button looking for local file which does not exist

### ISSUE THREAD

**Issue by Sacha00Z** [niceit/tabby-cloud-sync-settings#6]
My FTP server application logs show a successful connection, but Cloud Sync Settings show "Unable to connect with your settings". 

```
2021-12-22 15:05:48,181 sydpc-1193 proftpd[254457] sydpc-1193 (192.168.1.106[192.168.1.106]): mod_delay/0.7: no DelayOnEvent rules configured with "DelayTable none" in effect, disabling module
2021-12-22 15:05:48,181 sydpc-1193 proftpd[254457] sydpc-1193 (192.168.1.106[192.168.1.106]): FTP session opened.
2021-12-22 04:05:48,203 sydpc-1193 proftpd[254457] sydpc-1193 (192.168.1.106[192.168.1.106]): USER sacha: Login successful.
2021-12-22 04:05:48,216 sydpc-1193 proftpd[254457] sydpc-1193 (192.168.1.106[192.168.1.106]): FTP session closed.
```

I'm using ProFTPd version 1.36 on Ubuntu 20.04.3 LTS. Tabby 1.0.168 on Windows 11, installed via scoop.

Developer tools show the following message that is not reported to the UI:

```
{"level":"error","time":"12/22/2021, 3:16:58 PM","message":"Connection error. | Exception: Error: ENOENT: no such file or directory, open 'C:\\Users\\Sacha####\\scoop\\apps\\tabby\\1.0.168\\tabby-cloud-sync-settings\\src\\data\\test.txt'"}
```

Indeed, the folder 'C:\\Users\\Sacha####\\scoop\\apps\\tabby\\1.0.168\\tabby-cloud-sync-settings\\.' does not exist. Should you be looking in data\plugins?

Also, FYI: the "about" section of the configuration page points to the wrong github URL - so I hope I am reporting in the correct project!

**Comment by Sacha00Z** [comment]
Also, if you want to be totally portable, you should not be referencing folder 1.0.168, else everything will break on cleanup. This is quite possibly a tabby project issue which needs to be manually managed.

**Comment by niceit** [comment]
@Sacha00Z are you in development mode?

**Comment by Sacha00Z** [comment]
No, I don't think so. I'm not sure what that is.

I also think that there my be an issue with tabby:
https://github.com/Eugeny/tabby/issues/5251#issue-1086449462

**Comment by niceit** [comment]
I see, thank @Sacha00Z I will take a look into it

**Comment by Sacha00Z** [comment]
Cool. I think there are two issues here:
1. The missing file/folder
2. Error reporting. There's info in developer tools 'response' which should be piped to the UI.

**Comment by Sacha00Z** [comment]
Also, for completeness:

**To Reproduce:**

1. In a Windows Powershell prompt type: 'scoop install tabby' (requires scoop.sh)
2. run tabby and go to setting
3. Go to plugins and install cloud-settings-sync
4. Configure a connection to an ftp server
5. Turn on ftpd debug level logging
6. Open tabby developer tools
7. Navigate to "Setting Sync" tab in tabby and press "Test"
8. Errors are only properly reported in developer tools, plugin does to report debug info to UI

**Comment by Sacha00Z** [comment]
Hey Tran, looks like you just have a manifest issue. If I create test.txt manually (in the appropriate folder), the test succeeds.

```
~\scoop\apps\tabby\1.0.168>mkdir tabby-cloud-sync-settings
~\scoop\apps\tabby\1.0.168>cd tabby-cloud-sync-settings
~\scoop\apps\tabby\1.0.168\tabby-cloud-sync-settings>mkdir src
~\scoop\apps\tabby\1.0.168\tabby-cloud-sync-settings>cd src
~\scoop\apps\tabby\1.0.168\tabby-cloud-sync-settings\src>mkdir data
~\scoop\apps\tabby\1.0.168\tabby-cloud-sync-settings\src>cd data
~\scoop\apps\tabby\1.0.168\tabby-cloud-sync-settings\src\data>touch test.txt
~\scoop\apps\tabby\1.0.168\tabby-cloud-sync-settings\src\data>ls
test.txt
```

Then Test Connection:
==> "Your setting is valid."

**Comment by niceit** [comment]
Great! I think this is a common issue, because the Tabby is not tested with plug-in in scooped mode yet, then the path is having problem. All the settings will have this error on the WebDav, aws,... not just only FTP. Temporary you could do the trick to fix it right now. I will try to fix this one on next release.
