### ISSUE TITLE
Backblaze

### ISSUE THREAD

**Issue by blueturtleshells** [niceit/tabby-cloud-sync-settings#8]
It's not blackblaze :)

**Comment by niceit** [comment]
Closed by nonsense topic

**Comment by Luluno01** [comment]
> Closed by nonsense topic

No he means there is typo in "Blackblaze". It's [BACKblaze](https://www.backblaze.com/), not "bLackblaze".

**Comment by civarson** [comment]
> > Closed by nonsense topic
> 
> No he means there is typo in "Blackblaze". It's [BACKblaze](https://www.backblaze.com/), not "bLackblaze".

Yes, exactly. I apologize for not knowing how to properly file issues on here. 

--Not nonsense :)
