### ISSUE TITLE
SSH connections are lost when using cloud-sync-settings

### ISSUE THREAD

**Issue by z0ow** [niceit/tabby-cloud-sync-settings#9]
Hi~
My SSH connections in `Profile & connections` are all lost if I enable the cloud sync settings and use it to sync settings then reopen tabby. Is it a bug?

**Comment by niceit** [comment]
@z0ow if you synced to the cloud before, then choose Cloud to local, otherwise you should choose local to cloud for first time installed

**Comment by z0ow** [comment]
@niceit 

Hi, thanks for your concern.

I have chosen Cloud to local in tabby on another machine but the SSH connections are lost both of them. The problem is two machines have a lot of saved SSH connections, which means at least a SSH connection list exists in my tabby even a config is overridden another. I have disabled this plugin, deleted the remote JSON file, reconfigured SSH connections in one machine then enabled this plugin again. Now this problem is solved. Before that my tabby could not save any SSH connections because they will disappear after tabby restarted. I think it is more safety that cloud-sync-settings could save the old config file when it is first enabled.

**Comment by niceit** [comment]
@z0ow sorry for your inconvenience, I leave 2 options there because may be the cloud had the settings already and user wants to sync down first, or it's empty so you should choose Local -> Cloud to init the first settings. If you had the SSH connections already at local, you should sync Local -> Cloud for first time of usage. Then after that, once you reinstall the Tabby or new machine, just choose Cloud -> Local.

It's meant Local -> Cloud must be choose ONCE when you first time synced.
Regards.

**Comment by z0ow** [comment]
@niceit Don't worry, it does not take much inconvenience to me. This is the first time I use this plugin so probably I made some mistakes when syncing the settings. I just thought it would be better if cloud-sync-settings have a default feature that automatically backup old settings when it is first enabled.
Best regards.

**Comment by niceit** [comment]
@z0ow cool, I will note your idea for next fix. 
Thanks

**Comment by niceit** [comment]
Checkout new release

**Comment by z0ow** [comment]
@niceit Oh, I'm so sorry about not reply your messages, the past weeks have been so busy because of preparing for the Chinese new year. Happy Chinese Tiger New Year!

I have upgraded the cloud-sync-settings to the latest version and reconfigured sync settings to test this update. However, I can not receive a checkout message or any other information to notice where the backup configuration file is stored.

**Comment by z0ow** [comment]
In my opinion, it will be more friendly if a backup file path exists in the plugin information area or a message box pop out when performing the cloud-to-local operation.

Best regards.
